#!/bin/bash

mute(){
    dev="$1"; shift
    case "$dev" in
    	output ) 
            wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

            grep "false" <<< $(rancid "$PPID" get volume-output-mute) &> /dev/null \
                && rancid "$PPID" update volume-output-mute=true \
                || rancid "$PPID" update volume-output-mute=false
            ;;
	    input )
            wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

            grep "false" <<< $(rancid "$PPID" get volume-input-mute) &> /dev/null \
                && rancid "$PPID" update volume-input-mute=true \
                || rancid "$PPID" update volume-input-mute=false
			;;
    esac
}

change(){
    dev="$1"; shift
    case "$dev" in 
        output ) wpctl set-volume @DEFAULT_AUDIO_SINK@   "$1"% ;;
        input  ) wpctl set-volume @DEFAULT_AUDIO_SOURCE@ "$1"% ;;
    esac
}

get-volume(){
    dev="$1"; shift
    case "$dev" in 
        output )
            wpctl get-volume @DEFAULT_AUDIO_SINK@ |\
            cut -f 2 -d '.' |\
            cut -f1 -d ' '
            ;;
        input )
            wpctl get-volume @DEFAULT_AUDIO_SOURCE@ |\
            cut -f 2 -d '.' |\
            cut -f1 -d ' ' 
            ;;
    esac
}

command="$1"; shift
case $command in
    mute   ) mute "$@" ;;
    change ) change "$@" ;;
    get    ) get-volume "$@" ;;
esac
