#!/usr/bin/bash

grep "$1" <<< "$(rancid "$PPID" active-windows)" \
   && { rancid "$PPID" close "$1" && rancid "$PPID" update "${1}-reveal"="false" ; } \
   || { rancid "$PPID" open "$1" && rancid "$PPID" update "${1}-reveal"="true" ; }

