#!/bin/bash

calendar() {
    grep "calendar" <<< "$(rancid active-windows)" \
        && { rancid close calendar && rancid update cal-reveal="false" ; } \
        || { rancid open calendar  && rancid update cal-reveal="true"  ; }
}

volume(){
    grep "volume" <<< "$(rancid active-windows)" \
        && { rancid close volume && rancid update volume-reveal="false" ; } \
        || { rancid open volume  && rancid update volume-reveal="true"  ; }
}

case $1 in
    "calendar" ) calendar ;; 
    "volume" ) volume ;;
esac
