#!/bin/bash

mute(){

    dev="$1"; shift

    case "$dev" in
    	output ) 
	    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle  

	    grep "volume-output-mute: false" <<< $(rancid state) &> /dev/null \
		&& rancid update volume-output-mute=true \
		|| rancid update volume-output-mute=false
					    ;;
	input )
	    wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle  

	    grep "volume-input-mute: false" <<< $(rancid state) &> /dev/null \
		&& rancid update volume-input-mute=true \
		|| rancid update volume-input-mute=false
			    ;;
    esac
}

command="$1"; shift
case $command in
    mute ) mute "$@";;

esac
